name: Job4j Social Media API

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Generate report
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: app/build/reports/coverage/debug
      - name: Download test reports folder
        uses: actions/download-artifact@v3
        with:
          name: report
          path: app/build/reports/coverage/debug
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: '81a425a1-5bfc-4b12-ba48-cc730998d5bb'
        with:
          files: "app/build/reports/coverage/debug/report.xml"