name: Job4j Social Media API

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: '81a425a1-5bfc-4b12-ba48-cc730998d5bb'
      - name: Upload test report
        uses: actions/upload-artifact@v1
        with:
          path: build/reports/tests/test/
          name: Test Report
#          retention-days: 14
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          path: build/reports/jacoco/test/
          name: Coverage Report
#          retention-days: 14