name: Job4j Social Media API

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Generate Report
        run: |
          pip install codecov
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
          codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.0
        env:
          token: '81a425a1-5bfc-4b12-ba48-cc730998d5bb'
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          files: /home/runner/work/SIESTAstepper/SIESTAstepper/coverage.xml
          flags: tests